### ISSUE TITLE
firmware update question

### ISSUE THREAD

**Issue by chaos4ros2** [micro-ROS/micro-ROS_crazyflie_demo#17]
## Issue template

- Hardware description: Crazyflie 2.1
- RTOS: freeRTOS
- Installation type: micro_ros_setup
- Version or commit hash: foxy

#### Steps to reproduce the issue
I'm trying to run the micro-ros demo with crazyflie2.1

1. Run the docker compose and build with 
  ```
  docker-compose run --rm cf_builder
  ros2 run micro_ros_setup configure_firmware.sh crazyflie_demo 
  ros2 run micro_ros_setup build_firmware.sh
 ```
![Screenshot from 2021-08-26 07-05-48](https://user-images.githubusercontent.com/80691913/130880761-83d625d4-edd8-49d9-b6bb-beabbd7bd0f0.png)

2. Put Crazyflie in DFU mode and check with 
 ```
lsusb
```
The terminal outside the container is in DFU mode but the terminal inside container is in BOOTLOADER mode like these
  
![Screenshot from 2021-08-26 06-44-43](https://user-images.githubusercontent.com/80691913/130879613-75ea2389-42be-4c1b-aed3-95376ad0b490.png)

3. I can only flash the firmware inside the container so flash the micro-ROS firmware with 
```
 ros2 run micro_ros_setup flash_firmware.sh
 ```

#### Expected behavior
micro-ROS firmware is flashed successfully and Connect to Crazyflie successfully. 

#### Actual behavior
Messages showed in terminal loos okay but when I connected to Crazyflie with cfclient (after docker-compose up -d), Crazyflie turned into 「Self test fail」(The right front LED (1) is repeatedly blinking five short red pulses with a longer pause between groups.)
![Screenshot from 2021-08-26 07-06-53](https://user-images.githubusercontent.com/80691913/130880764-09cf3c6b-4012-440c-9619-94319b7adf2e.png)

#### Additional information
Is there something wrong and how can I check everything is ok?

**Comment by pablogs9** [comment]
Can you share the output of the micro-ROS Agent with `-v6` flag enabled?

**Comment by chaos4ros2** [comment]
I'm not confident that this way of doing is good. based on [this issue](https://github.com/micro-ROS/micro-ROS_crazyflie_demo/issues/12#issue-777758206) I typed
```
sudo docker exec -it micro-ros_crazyflie_demo_cf_agent_1 /bin/bash
ros2 run micro_ros_agent micro_ros_agent serial --dev /dev/pts/checked_number -v6
```
and in another terminal
```
sudo docker exec -it micro-ros_crazyflie_demo_cf_client_1 /bin/bash
cfclient
```

here is the output
![Screenshot from 2021-08-27 01-10-43](https://user-images.githubusercontent.com/80691913/131000941-711f470f-1279-4f74-a4b5-78f94ffe46af.png)

Everytime I pushed scan button, crazyflie rebooted and turned into「Self test fail」state.

**Comment by chaos4ros2** [comment]
I feel like I understood a little.

I tried and confirmed the following：

1. Can't put Crazyflie 2.1 in recovery bootloader mode like this [video](https://www.youtube.com/watch?v=is5Hy9GlWAo).
    => There seems to be a problem with bootloader.

2. Bin bootloader recovery follow the [tutorial](https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/development/dfu/). You can see the bootloader uses address 0x08000000.
![bootloader_github](https://user-images.githubusercontent.com/80691913/131211796-95b3945c-c819-4a75-b94c-634931a58633.png)

3. BIN file DFU flashing. The firmware uses address 0x08004000. 
![firmware_github](https://user-images.githubusercontent.com/80691913/131211797-dfbc75eb-3894-45c9-8ff4-63f07dfeaa27.png)

4. I flashed the micro-ROS fireware into address 0x08000000 that is prepared for bootloader.
![micro-ros](https://user-images.githubusercontent.com/80691913/131212035-ed36aeaf-3228-4fdc-9645-cf0c6b9a1608.png)

So overflash may be the problem and here is my question：
How can I flash the micro-ROS firmware with DFU mode in a docker container or flash it to a specified address.

**Comment by Acuadros95** [comment]
Hi @chaos4ros2,

I don't think thats the problem, as specified on [this link](https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/development/dfu/):
`If the Crazyflie 2.X firmware was compiled with CLOAD=1 (default option) the binary should be flashed after the bootloader at address 0x08004000.`

But we are building with `CLOAD=0`: [link](https://github.com/micro-ROS/micro_ros_setup/blob/galactic/config/freertos/crazyflie21/build.sh#L36).

I think the problem may be related to the interaction between the demo and the agent. I am currently working on this, will come back with updates.

Anyway, you can change the address by modifying this line: https://github.com/micro-ROS/micro_ros_setup/blob/galactic/config/freertos/crazyflie21/flash.sh#L5

**Comment by chaos4ros2** [comment]
Hi @Acuadros95,

> I don't think thats the problem, as specified on this link:
If the Crazyflie 2.X firmware was compiled with CLOAD=1 (default option) the binary should be flashed 
after the bootloader at address 0x08004000.
But we are building with CLOAD=0: link.

I have learned a lot from you. Thank you very much.

> I think the problem may be related to the interaction between the demo and the agent. I am currently working on this, will come back with updates.

This will be very helpful for me! I am waiting for you to come back.

> Anyway, you can change the address by modifying this line: https://github.com/micro-ROS/micro_ros_setup/blob/galactic/config/freertos/crazyflie21/flash.sh#L5

I learn something new again, thanks for teaching me the way to modify address.
Because I don't have any experience with embedded system, I am going to try it after
testing your updates.

**Comment by Acuadros95** [comment]
Hello @chaos4ros2, 

We just made a big update on this demo, please update your repos/dockers and give it a try. 
Feel free to ask any questions and give feedback.

**Comment by chaos4ros2** [comment]
Hello Acuadros95,

I am trying your update and getting stuck in [How to prepare the Raspberry Pi applications?](https://github.com/micro-ROS/micro-ROS_crazyflie_demo#how-to-prepare-the-raspberry-pi-applications)

I got a error like blow when I typed
```
sudo docker run -ti --rm microros/base:galactic
```

error:
```
chaos@chaos:~/ros2/drone_ws/micro-ROS_crazyflie_demo$ sudo docker run -ti --rm microros/base:galactic
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
standard_init_linux.go:228: exec user process caused: exec format error
```

**Comment by chaos4ros2** [comment]
Sorry to bother you again. 
I have another question about how to control drone with only one Crazyradio PA.

I found that two channels are used in crazyflie's firmware.
[One](https://github.com/micro-ROS/freertos_apps/blob/galactic/apps/crazyflie_demo/app.c#L116) for publishing sensor data and [the other one](https://github.com/micro-ROS/freertos_apps/blob/galactic/apps/crazyflie_demo/app.c#L305) for commanding crazyflie with a controller.
[The tutorial](https://github.com/micro-ROS/micro-ROS_crazyflie_demo#hardware) says it is just need one Crazyradio PA, but is it possible to use two channels with one Crazyradio PA?

**Comment by Acuadros95** [comment]
> I am trying your update and getting stuck in How to prepare the Raspberry Pi applications?

This tutorial is intended to cross-compile the applications from a regular computer, and I guess you are running the docker inside the raspberry.

> I found that two channels are used in crazyflie's firmware.

Yes, the crazyflie demo is a very specific use case, where two different Crazyradios are used. If you want to test micro-ROS, I advise you to try the position publisher example instead.

You can use micro-ROS and command the crazyflie with a controller using only one crazyflie with that example.
You can also just run the demo and just connect to the [main task](https://github.com/micro-ROS/freertos_apps/blob/galactic/apps/crazyflie_demo/app.c#L116).

**Comment by chaos4ros2** [comment]
I ran two demos and confirm the results.

Tf datas are correctly plotted in rviz2 in [crazyflie_demo](https://github.com/micro-ROS/freertos_apps/blob/galactic/apps/crazyflie_demo/app.c) sample and 
/drone/attitude(odometry) are correctly sended by drone in [crazyflie_position_publisher](https://github.com/micro-ROS/freertos_apps/blob/galactic/apps/crazyflie_position_publisher/app.c#L57) sample. And I can command the crazyflie with a controller at the same time !

crazyflie_demo's result :

![crazyflie](https://user-images.githubusercontent.com/80691913/137617239-2bd6534e-a99f-419b-ac56-18d9cdac2a11.png)

crazyflie_position_publisher's result :

![victory](https://user-images.githubusercontent.com/80691913/137617289-831b2598-ae7c-4cfc-b1fb-6029b75d431c.png)

Thanks for the amazing demo and answer. It motivates me to study ROS2 and use micro-ROS.
I am going to master micro-ROS via these demos.

I also created a PR to fix the node.js vision problem during set up cf_visualizer container.
